# Generated by Django 3.2.6 on 2021-10-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('retail_price', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('discounted_price', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('image', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('product_rating', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('overall_rating', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('brand', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
    ]
